[package]
name = "geomusica_wasm"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/geometry/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.84"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
